#!/bin/bash

regex=
INSTALL_DIR=$(dirname $0)
source $INSTALL_DIR/config.py

MERRA_hourly_path=${DATA_DIR}/temperature_humidity/hourly/
HDF5_hourly_path=${DATA_DIR}/precipitation/hourly_hdf5/

humidity_daily_path=${DATA_DIR}/temperature_humidity/daily/humidity/
temp_daily_path=${DATA_DIR}/temperature_humidity/daily/Temperature/
OMI_AURA_daily_path=${DATA_DIR}/OMNO2d_003/
HDF5_daily_path=${DATA_DIR}/precipitation/daily/

get_data()
{
  if test -z "$2";
  then
    echo "No data currently exists at $4"
    echo "To get all current data, run"
    echo "${INSTALL_DIR}/get-nasa-data --username [your NASA username] --password [your NASA password] -l $3 --matches="*" -o $4"
    exit 2
  fi
  output=$(${INSTALL_DIR}/next-filename -f "$2" -e "$1" -d $5 "$3")
  new_name=$(echo ${output} | cut -d '|' -f1)
  new_url=$(echo ${output} | cut -d '|' -f2)
  ${INSTALL_DIR}/get-nasa-data --username "Synyster" --password "Jaiganesh01$" -l ${new_url} --matches="*${new_name}*" -o $4 >> "${log_file}" 2>&1
}

get_latest_data()
{
  # Get temperature and humidity data from NASA archives
  data_path=$1
  grep_exp=$2
  # Define a regular expression that specifies the location of the date/time information in the URL to retrieve data
  URL=$3
  # Define a regular expression that specifies the location of the date/time information in data file names
  regex=$4

  duration=$5
  if test -z "${duration}";
  then
    let duration=1*24*60;
  fi

  txt_file="${data_path}/new_files.txt"

  while true;
  do
    prev_tail=$(ls ${data_path} | grep "${grep_exp}" | grep -v "new_files_" | tail -1)
    # Get the data satisfying the regexes, specifying a duration of 30 minutes for precipitation data since it is recorded for every half hour interval and one day for everything else
    get_data "${regex}" "${prev_tail}" "${URL}" "${data_path}" "${duration}"
    new_tail=$(ls ${data_path} | grep "${grep_exp}" | grep -v "new_files_" | tail -1)
    # If no new files were downloaded, exit the loop and move to data processing, otherwise put them in the txt file to be processed
    if test "${prev_tail}" == "${new_tail}";
    then
      break;
    else
      echo "${new_tail}" >> "${txt_file}"
    fi
  done
}

# Clear the data log from yesterday's collection/processing
> ${log_file}

# Activate the created gdal environment, which has python 3.8 installed
eval "$(conda shell.bash hook)"
conda activate gdal

# Run the above functions

# Process NO2 Data
get_latest_data ${OMI_AURA_daily_path} "OMI-Aura_L3" "https://acdisc.gesdisc.eosdis.nasa.gov/data/Aura_OMI_Level3/OMNO2d.003/%Y/" "OMI-Aura_L3-OMNO2d_%Ym%m%d_v003-"
if test $? -eq 0; then
    ${INSTALL_DIR}/processEnvFactors -f 'NO2' -d "${OMI_AURA_daily_path}/new_files.txt" >> ${log_file} 2>&1
    if test $? -eq 0; then
        > "${OMI_AURA_daily_path}/new_files.txt"
    fi
fi

# Process temperature/humidity data
get_latest_data ${MERRA_hourly_path} "MERRA2_400" "https://goldsmr4.gesdisc.eosdis.nasa.gov/data/MERRA2/M2T1NXSLV.5.12.4/%Y/%m/" "MERRA2_400.tavg1_2d_slv_Nx.%Y%m%d.nc4"
if test $? -eq 0; then
    ${INSTALL_DIR}/HourlyToDaily >> ${log_file} 2>&1
    if test $? -eq 0; then
        > "${MERRA_hourly_path}/new_files.txt"
        ${INSTALL_DIR}/processEnvFactors -f 'Humidity' -d "${humidity_daily_path}/new_files.txt" >> ${log_file} 2>&1
        if test $? -eq 0; then
            > "${humidity_daily_path}/new_files.txt"
            ${INSTALL_DIR}/processEnvFactors -f 'Temper_T2MMEAN' -d "${temp_daily_path}/new_files.txt" >> ${log_file} 2>&1
            if test $? -eq 0; then
                > "${temp_daily_path}/new_files.txt"
            fi
        fi
    fi
fi

# Process precipitation data
# Download latest data according to the current data file
get_latest_data ${HDF5_hourly_path} "3B-HHR-E" "https://gpm1.gesdisc.eosdis.nasa.gov/data/GPM_L3/GPM_3IMERGHHE.06/%Y/%j/" "3B-HHR-E.MS.MRG.3IMERG.%Y%m%d-S%H%M%S" 30
if test $? -eq 0; then
    # Convert hourly data to daily data
    ${INSTALL_DIR}/HourlyToDaily >> ${log_file} 2>&1
    if test $? -eq 0; then
        # Convert daily files to CSVs (shapefile corresponding)
        > "${HDF5_hourly_path}/new_files.txt"
        ${INSTALL_DIR}/processEnvFactors -f 'Precipitation' -d "${HDF5_daily_path}/new_files.txt" >> ${log_file} 2>&1
        if test $? -eq 0; then
            # Clear all txt files so that yesterday's files are not processed again
            > "${HDF5_daily_path}/new_files.txt"
        fi
    fi
fi


